---
- name: Install global NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ npm_packages }}"

- name: Install asdf dependencies
  vars:
    asdf_init_shell: false
    asdf_plugins:
      - name: "nodejs"
        repository: "https://github.com/asdf-vm/asdf-nodejs.git"
        versions:
          - 14.5.0
        global: 14.5.0
    asdf_plugins:
      - name: "postgres"
        repository: "https://github.com/smashedtoatoms/asdf-postgres"
        versions:
          - 9.6.23
        global: 9.6.23
    asdf_plugins:
      - name: "gcloud"
        repository: ""
        versions:
          - 360.0.0
        global: 360.0.0
  include_role:
    name: markosamuli.asdf
